# Generated by Django 6.0.1 on 2026-01-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-trophy', help_text='Font Awesome icon class (e.g., fas fa-code, fas fa-trophy)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Technical Achievement',
                'verbose_name_plural': 'Technical Achievements',
                'ordering': ['order', 'title'],
            },
        ),
    ]
